### ISSUE TITLE
Bullet type does not update if incrementing/decrementing with insert-mode <C-t>/<C-d>

### ISSUE THREAD

**Issue by mtrajano** [dkarter/bullets.vim#117]
Not sure if this is intentional or not but I assume it would work the same as incrementing/decrementing with `<`/`>` in normal mode

To reproduce:
```
- some list
```

Create an item under `some list` and increment using `<C-t>` this will not change the bullet type, then switch to normal mode and increment with `>`, you will see that the bullet type changes

**Comment by kaymmm** [comment]
Can you provide more details of what happens and what you expect to happen? I believe I just tested the same thing that you described and the bullet type changes with both `<C-t>` and `>` the same way.

```
- some list|
```
`Enter`:
```
- some list
- |
```
`<C-t>`:
```
- some list
  * |
```
instead of `<C-t>` typing `>` in normal mode gives the same result:
```
- some list
" Enter
- some list
- |
" <Esc>>
- some list
  *
```

**Comment by Enchoseon** [comment]
I also experienced `<C-t>` and `>` behaving differently, it turned out to be [Vimwiki's](https://github.com/vimwiki/vimwiki) conflicting bullet-point mappings.

I disabled Vimwiki's bullet-point keymappings with—
```vimscript
let g:vimwiki_key_mappings = { "lists": 0 }
```

—and `<C-t>`/`<C-d>` behaved as expected.

If you have [Telescope](https://github.com/nvim-telescope/telescope.nvim) you can check for conflicting mappings from other plugins with `:Telescope keymaps`, query for `C-t`, and check what comes up.
