### ISSUE TITLE
Pressing o on non-list items moves the last character of the current line into the next

### ISSUE THREAD

**Issue by dareenzo** [dkarter/bullets.vim#31]
Pressing o on non-list items moves the last character of the current line into the next

![file](https://user-images.githubusercontent.com/6130991/54604406-53c80500-4a4f-11e9-8ea2-351088829ee6.gif)

**Comment by dkarter** [comment]
Hi @dareenzo,

Thanks for the bug report. I tried replicating it and was unable to.

![demo](https://i.imgur.com/ACWpsvn.gif)

I suspect this is caused by another plugin (perhaps you have a pandoc plugin?)

Can you please provide a minimal vimrc to help reproduce the issue?

---

## Example minimal vimrc

```vim
syntax on
call plug#begin('~/.vim/bundle')

Plug 'dkarter/bullets.vim'
Plug 'some-other/plugin'

call plug#end()
```

Save it to a file and then `nvim -u .debug-vimrc test.md`

**Comment by dareenzo** [comment]
Stripping down the configuration to its minimum, as suggested above, shows the error is not with the plugin. 

I don't know yet what is happening since there's only one `o` mapping, that is related to the plugin, but I probably should look elsewhere

Thanks
