### ISSUE TITLE
Add support for AsciiDoc(tor) lists

### ISSUE THREAD

**Issue by mykoza** [dkarter/bullets.vim#35]
Hi,
First, I have to say that this is very nice plugin. I have been using it for note-taking in Markdown, but recently decided to switch to AsciiDoc.

Would it be possible to add support for AsciiDoc lists to this plugin?

If you are not familiar with them, they are similar to OrgMode headings, in that item nesting is done by adding more "bullets". Unordered lists use `*` and ordered lists use `.`.

Example unordered list:

```
* Unordered item
** Nested item
** Next nested item
* Level 1 item again
```

Example ordered list:

```
. Ordered item
.. Nested item
.. Next nested item
. Level 1 item again
```

For more information you can check [AsciiDoc Documentation](https://www.methods.co.nz/asciidoc/chunked/ch17.html) or [AsciiDoctor Documentation](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists).

The plugin already has basic support for `*` lists thanks to #18 , but no support for `.` or nesting (i.e. indenting using mappings), unless I just wasn't able to figure it out, in which case I'm sorry for opening issue.

**Comment by dkarter** [comment]
Hi @mykoza thank you for reaching out!
[I have opened a PR to add support for AsciiDoc](https://github.com/dkarter/bullets.vim/pull/36). All the tests pass locally, but one of them fails in CI, not sure why yet, as I haven't had a lot of time to put into this.

As far as indentation go, I currently don't have any mappings for bullet indentation, and in the plugin's documentation I recommended people use Vim's built-in `<C-d>` and `<C-t>` (in insert mode), to indent/de-indent their bullets. I'm not sure what the ideal behavior would be for this specific use-case, but my initial thought is:

1. Override `<C-d>` and `<C-t>` in insert mode
2. When those mappings are used, check if the current line is either `*` or `.`
3. if it is, prepend another `*` or `bullet`, otherwise send the original user mappings for those.

I want this to be minimally intrusive, so there would need to be an option to disable and enable it, the user would need to set up an `autocmd` for the AsciiDoc filetype to enable it in the buffer, and to make it easy I can have an example of such command in the docs.

Any thoughts on this approach?

**Comment by mykoza** [comment]
Thanks for the reply.

Before I opened the issue, I tried to do almost exactly what you suggested, on my own, but as I am pretty much a beginner (especially in vim script) I only managed to get it working on one line in normal mode using `execute 'normal!...'`. I had some problems with insert mode and I have no idea how to make it working with number of lines at the same time.

**Comment by mykoza** [comment]
Hi again,

I opened pull request #37. I tried to write it the best I could, but I'm sure it can be done better.

After setting variable in .vimrc it maps to `<C-t>, <C-d>, >>, <<`. Works only inside AsciiDoc lists, when `FileType` is set to `asciidoc*`. Outside it retains default Vim behaviour.

User can define their own mappings, or enable it only in insert mode.

**Comment by mykoza** [comment]
Hey @dkarter, any feedback on that PR? Is it any good?

**Comment by dkarter** [comment]
Basic support for AsciiDoc has been merged. Let's move additional discussion over to the PR you have open.
