### ISSUE TITLE
Support CommonMark nested lists

### ISSUE THREAD

**Issue by bockel** [dkarter/bullets.vim#46]
The current indent/dedent scheme in bullets.vim does not support the CommonMark spec for nested ordered lists.

The new [CommonMark](https://spec.commonmark.org/0.29/) spec changes the way nested lists are handled beneath an ordered list. Originally, a nested list could just be indented by 2 spaces, but the updates require that there is one space in addition to the list marker: https://spec.commonmark.org/0.29/#list-items

For example, this code is valid in most markdown:

```md
1. Ordered list item
  - sub item with 2 spaces
  - another 2 space item
```

CommonMark states that this must now be written with `len("1.") + 1=3` indent:

```md
1. Ordered list item
   - Now indented by 3 spaces
   - Another 3 space ident
```

**Comment by dkarter** [comment]
Indentation is not actually done by this plugin. `<C-d>` and `<C-t>` are built into Vim.

I'm hesitant to add functionality to this plugin that would be very specific to markdown because that could affect other cases where bullets is used outside of markdown.

Perhaps you can add something to your vimrc to take care of that? e.g. autocmd for markdown filetypes that would change the behavior of `<C-d>` and `<C-t>` in the buffer.

**Comment by dkarter** [comment]
@bockel Thanks to @kaymmm, in #54 Bullets.vim started handling indentation. The good news is that @kaymmm used Vim's built-in indentation settings so you should be able to easily change your settings like so:

```vim
:set expandtab
:set shiftwidth=3
``` 

You can even have that as an autocmd for Markdown files like so:

```vim
augroup Markdown
  autocmd!
  
  " Use spaces instead of tabs
  autocmd FileType markdown setlocal expandtab
  " Change indentation level to match CommonMark specs
  autocmd FileType markdown setlocal shiftwidth=3
endgroup
```

Here's a demo:
![2020-05-05 11 39 47](https://user-images.githubusercontent.com/551858/81092574-66590400-8ec6-11ea-9f9b-d109311a8a43.gif)
